export * as skillring1 from './skillring1.png'
export * as skillring2 from './skillring2.png'
export * as skillring3 from './skillring3.png'

export * as ring1 from './ring1.png'
export * as ring2 from './ring2.png'
export * as ring3 from './ring3.png'
export * as ring4 from './ring4.png'
export * as pocket from './pocket.png'

export * as pendant1 from './pendant1.png'
export * as pendant2 from './pendant2.png'
export * as weapon from './weapon.png'
export * as belt from './belt.png'
export * as medal from './medal.png'

export * as hat from './hat.png'
export * as face from './face.png'
export * as eye from './eye.png'
export * as top from './top.png'
export * as bottom from './bottom.png'

export * as earring from './earring.png'
export * as shoulder from './shoulder.png'
export * as glove from './glove.png'
export * as cape from './cape.png'
export * as shoe from './shoe.png'

export * as emblem from './emblem.png'
export * as badge from './badge.png'
export * as secondary from './secondary.png'
export * as heart from './heart.png'

export * as ring1_drop from './ring1_drop.png'
export * as ring2_drop from './ring2_drop.png'
export * as ring3_meso from './ring3_meso.png'
export * as ring3_drop from './ring3_drop.png'
export * as ring4_meso from './ring4_meso.png'
export * as ring4_drop from './ring4_drop.png'
export * as pendant1_drop from './pendant1_drop.png'
export * as pendant2_drop from './pendant2_drop.png'
export * as face_meso from './face_meso.png'
export * as face_drop from './face_drop.png'
export * as eye_meso from './eye_meso.png'
export * as eye_drop from './eye_drop.png'
export * as earring_meso from './earring_meso.png'
export * as earring_drop from './earring_drop.png'
